# используем язык java. Travis CI поддерживает другие языки тоже.
env:
  global:
    - CODECOV_TOKEN=2b8be1aa-4be3-453e-bd78-52e2766c15e8
language: java
jdk:
  - openjdk14
services:
  - postgresql
before_install:
  - psql -c 'create database todo;' -U postgres
# используем режим обычного пользователя для сборки проекта.
sudo: false
# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 2b8be1aa-4be3-453e-bd78-52e2766c15e8
# Отправлять уведомление на почту mailto:youremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -mailto:pesterevvv@gmail.com
    on_success: never # default: change
    on_failure: always # default: always