CREATE SEQUENCE IF NOT EXISTS item_sq MINVALUE 1 START WITH 1;
CREATE TABLE IF NOT EXISTS item (
   id INTEGER NOT NULL DEFAULT nextval('item_sq'),
   description TEXT NOT NULL,
   created TIMESTAMP DEFAULT now(),
   done SMALLINT NOT NULL DEFAULT 0,
   CONSTRAINT pk_item PRIMARY KEY(id)
);